<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LoginWrong email or passwo</name>
   <tag></tag>
   <elementGuidId>fb4768b9-53a0-442e-90f0-963beb6e54a5</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LoginWrong email or password.EmailPasswordLog inForgot the password?</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;render-target&quot;)/div[@class=&quot;online
					xs
					AppNav-closed
					app&quot;]/div[@class=&quot;app__content&quot;]/main[@class=&quot;app__content__main&quot;]/div[@class=&quot;row&quot;]</value>
   </webElementProperties>
</WebElementEntity>
