<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Log in</name>
   <tag></tag>
   <elementGuidId>99df7efb-689e-47ef-a840-a8e9de460e81</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/auth/login</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Log in</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;render-target&quot;)/div[@class=&quot;online
					xs
					AppNav-closed
					app&quot;]/div[@class=&quot;app__content&quot;]/header[@class=&quot;app__content__header&quot;]/nav[@class=&quot;app__content__header--online&quot;]/ul[@class=&quot;app__content__header--online__subnav&quot;]/li[2]/div[@class=&quot;user-actions&quot;]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
